[2025-03-19T20:23:25.279+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-19T20:23:25.313+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: extract_f1_drivers_to_s3.upload_to_s3 manual__2025-03-19T20:23:20.867220+00:00 [queued]>
[2025-03-19T20:23:25.327+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: extract_f1_drivers_to_s3.upload_to_s3 manual__2025-03-19T20:23:20.867220+00:00 [queued]>
[2025-03-19T20:23:25.342+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-03-19T20:23:25.364+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): upload_to_s3> on 2025-03-19 20:23:20.867220+00:00
[2025-03-19T20:23:25.373+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=591) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-19T20:23:25.375+0000] {standard_task_runner.py:72} INFO - Started process 592 to run task
[2025-03-19T20:23:25.378+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'extract_f1_drivers_to_s3', 'upload_to_s3', 'manual__2025-03-19T20:23:20.867220+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpv2hf3iif']
[2025-03-19T20:23:25.380+0000] {standard_task_runner.py:105} INFO - Job 9: Subtask upload_to_s3
[2025-03-19T20:23:25.445+0000] {task_command.py:467} INFO - Running <TaskInstance: extract_f1_drivers_to_s3.upload_to_s3 manual__2025-03-19T20:23:20.867220+00:00 [running]> on host f4458d2d3a43
[2025-03-19T20:23:25.561+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='extract_f1_drivers_to_s3' AIRFLOW_CTX_TASK_ID='upload_to_s3' AIRFLOW_CTX_EXECUTION_DATE='2025-03-19T20:23:20.867220+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-19T20:23:20.867220+00:00'
[2025-03-19T20:23:25.563+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-19T20:23:25.605+0000] {base.py:84} INFO - Retrieving connection 'aws_default'
[2025-03-19T20:23:25.607+0000] {connection_wrapper.py:325} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') credentials retrieved from login and password.
[2025-03-19T20:23:28.140+0000] {hook.py:208} WARNING - Data lineage tracking is disabled. Register a hook lineage reader to start tracking hook lineage.
[2025-03-19T20:23:28.144+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-03-19T20:23:28.160+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-19T20:23:28.161+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=extract_f1_drivers_to_s3, task_id=upload_to_s3, run_id=manual__2025-03-19T20:23:20.867220+00:00, execution_date=20250319T202320, start_date=20250319T202325, end_date=20250319T202328
[2025-03-19T20:23:28.248+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-19T20:23:28.273+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-19T20:23:28.291+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
