[2025-03-19T20:01:26.621+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-19T20:01:26.643+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: extract_f1_drivers_to_s3.extract_data manual__2025-03-19T20:01:24.317178+00:00 [queued]>
[2025-03-19T20:01:26.653+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: extract_f1_drivers_to_s3.extract_data manual__2025-03-19T20:01:24.317178+00:00 [queued]>
[2025-03-19T20:01:26.655+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-03-19T20:01:26.673+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): extract_data> on 2025-03-19 20:01:24.317178+00:00
[2025-03-19T20:01:26.688+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=295) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-19T20:01:26.690+0000] {standard_task_runner.py:72} INFO - Started process 296 to run task
[2025-03-19T20:01:26.690+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'extract_f1_drivers_to_s3', 'extract_data', 'manual__2025-03-19T20:01:24.317178+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpu_mflt41']
[2025-03-19T20:01:26.691+0000] {standard_task_runner.py:105} INFO - Job 5: Subtask extract_data
[2025-03-19T20:01:26.761+0000] {task_command.py:467} INFO - Running <TaskInstance: extract_f1_drivers_to_s3.extract_data manual__2025-03-19T20:01:24.317178+00:00 [running]> on host f4458d2d3a43
[2025-03-19T20:01:26.878+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='extract_f1_drivers_to_s3' AIRFLOW_CTX_TASK_ID='extract_data' AIRFLOW_CTX_EXECUTION_DATE='2025-03-19T20:01:24.317178+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-19T20:01:24.317178+00:00'
[2025-03-19T20:01:26.879+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-19T20:01:29.505+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-03-19T20:01:29.517+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-19T20:01:29.518+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=extract_f1_drivers_to_s3, task_id=extract_data, run_id=manual__2025-03-19T20:01:24.317178+00:00, execution_date=20250319T200124, start_date=20250319T200126, end_date=20250319T200129
[2025-03-19T20:01:29.567+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-19T20:01:29.600+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-19T20:01:29.619+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
